### ISSUE TITLE
Path to timelapse for upload

### ISSUE THREAD

**Issue by dansxmods** [ryanfox1985/OctoPrint-Youtube-Timelapse#5]
Just wondering if I have a custom path set (an NFS share on my Ubuntu server) will this get the path from the timelapse settings or is it just looking in the default shipped path from factory install?

**Comment by ryanfox1985** [comment]
Hello, I think if your NFS shared folder is mounted where ever you are running Octoprint, is not a problem because the plugin is using the absolute path file, like: `/home/pi/.octoprint/timelapse/XXXXXXX_20210310162340.mp4 `. In this case the plugin don't care about `/home/pi/.octoprint/timelapse` is mounted.

**Comment by dansxmods** [comment]
Ah ok, then that would explain why my time-lapse didn't upload. I have changed the path in octoprint folders setting. Any chance you could tell where in the code I can set the path for this plugin?

**Comment by ryanfox1985** [comment]
can you post your config?

Here is where I receive the event from the framework to upload the video file:
https://github.com/ryanfox1985/OctoPrint-Youtube-Timelapse/blob/master/octoprint_youtube_timelapse/__init__.py#L164-L173

**Comment by dansxmods** [comment]
Sorry for the late reply, looks like you added an option in the latest update to choose your folder which would solve this issue, nice work.

**Comment by ryanfox1985** [comment]
ok I will close the issue.
